# Generated by Django 2.0 on 2018-10-17 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_agentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentstatus',
            name='agent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
